### PR TITLE
Fix naming inconsistency

### PR DESCRIPTION
**Pull request by errm**

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
*If you're new, read the [guidelines]
(https://github.com/reevoo/guidelines/blob/master/pull_requests.md).*

Good code is **tested**, **designed for change**, **easy to understand**
and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [ ] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need
tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [ ] The code is well-designed and able to cope with change.
- [ ] The code is easy to understand.
- [ ] Tests cover happy and unhappy paths in the code.
- [ ] Tests are green on CI (or pulled/tested on your machine).

**Comment by errm** [comment]
Also the github repo should be renamed, and the gem should be pushed to rubygems to sqaut the name.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
I don't see any comments on your Pull Request.

Are you too good for code reviews now?
No. No you aren't.

Maybe you forgot to say who reviewed it. That's fine, but let me know.

**Pull request merged**
